AGENT_STATUS_LOGGED_OUT = "Logged Out"
AGENT_STATUS_AVAILABLE = "Available"
AGENT_STATUS_AVAILABLE_ON_DEMAND = "Available (On Demand)"
AGENT_STATUS_ON_BREAK = "On Break"

AGENTS_STATUSES = [AGENT_STATUS_LOGGED_OUT, AGENT_STATUS_AVAILABLE, AGENT_STATUS_AVAILABLE_ON_DEMAND, AGENT_STATUS_ON_BREAK]
